export const AFFILIATED_PHARMACIES = [
  {
    id: 'ph1',
    name: 'Farmacia San José',
    rating: 4.8,
    address: 'Av. Francisco de Miranda, Caracas',
    zone: 'Chacao',
    deliveryTime: '30-45 min',
    isOpen: true,
    deliveryFee: 5.00,
    minOrder: 20.00,
  },
  {
    id: 'ph2',
    name: 'Farmatodo Las Mercedes',
    rating: 4.5,
    address: 'Calle París, Las Mercedes, Caracas',
    zone: 'Las Mercedes',
    deliveryTime: '45-60 min',
    isOpen: true,
    deliveryFee: 4.50,
    minOrder: 15.00,
  },
  {
    id: 'ph3',
    name: 'Farmacia La Trinidad',
    rating: 4.7,
    address: 'C.C. La Trinidad, Caracas',
    zone: 'La Trinidad',
    deliveryTime: '40-50 min',
    isOpen: true,
    deliveryFee: 6.00,
    minOrder: 25.00,
  }
]; 